### PR TITLE
Get full permalink from server side. It was being truncated client side ...

### PR DESCRIPTION
**Pull request by orourkebm**
...with long titles.

### CODE REVIEW

**Comment by orourkebm** [comment]
@bradtaylorsf 

Can we get this merged?

**Comment by orourkebm** [comment]
@bradtaylorsf 

Quick ping here. Are there any concerns?

**Comment by bradtaylorsf** [comment]
@orourkebm Just saw this... looking now

**Comment by orourkebm** [comment]
@bradtaylorsf 

No worries man, thanks for taking a look!

The Daily Caller has run into a few issues, and while they're forking the repo on their own to correct, I'd like to fix on our end as well for a show of good faith-- and also obviously to avoid this in the future

**Pull request merged**
